/*

    СТОЛИЦЫ СТРАН МИРА. Первая версия.
    Все данные хранятся в одной таблице

*/

USE master
GO
CREATE DATABASE BelhardTraining
    COLLATE Cyrillic_General_CS_AI
GO
USE BelhardTraining
GO

CREATE TABLE CountryCapital
(
    PartOfWorld varchar(20) NOT NULL,
    Country     varchar(30) NOT NULL,
    CapitalCity varchar(40) NOT NULL
)
GO

INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Австрия', 'Вена')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Албания', 'Тирана')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Андорра', 'Андорра-ла-Велья')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Белоруссия', 'Минск')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Бельгия', 'Брюссель')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Болгария', 'София')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Босния и Герцеговина', 'Сараево')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Ватикан', 'Ватикан')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Великобритания', 'Лондон')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Венгрия', 'Будапешт')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Германия', 'Берлин')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Греция', 'Афины')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Дания', 'Копенгаген')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Исландия', 'Рейкьявик')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Испания', 'Мадрид')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Италия', 'Рим')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Латвия', 'Рига')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Литва', 'Вильнюс')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Лихтенштейн', 'Вадуц')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Люксембург', 'Люксембург')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Македония', 'Скопье')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Мальта', 'Валлетта')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Молдавия', 'Кишинёв')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Монако', 'Монако')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Нидерланды', 'Амстердам')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Норвегия', 'Осло')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Польша', 'Варшава')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Португалия', 'Лиссабон')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Россия', 'Москва')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Румыния', 'Бухарест')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Сан-Марино', 'Сан-Марино')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Сербия', 'Белград')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Словакия', 'Братислава')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Словения', 'Любляна')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Украина', 'Киев')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Финляндия', 'Хельсинки')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Ирландия', 'Дублин')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Франция', 'Париж')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Хорватия', 'Загреб')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Черногория', 'Подгорица')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Чехия', 'Прага')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Швейцария', 'Берн')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Швеция', 'Стокгольм')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Европа', 'Эстония', 'Таллин')

INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Азербайджан', 'Баку')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Армения', 'Ереван')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Афганистан', 'Кабул')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Бангладеш', 'Дакка')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Бахрейн', 'Манама')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Бруней', 'Бандар-Сери-Бегаван')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Бутан', 'Тхимпху')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Восточный Тимор', 'Дили')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Вьетнам', 'Ханой')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Грузия', 'Тбилиси')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Израиль', 'Иерусалим')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Индия', 'Дели (Нью-Дели)')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Индонезия', 'Джакарта')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Иордания', 'Амман')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Ирак', 'Багдад')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Иран', 'Тегеран')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Йемен', 'Сана')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Казахстан', 'Астана')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Камбоджа', 'Пномпень')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Катар', 'Доха')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Кипр', 'Никосия')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Киргизия', 'Бишкек')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'КНДР', 'Пхеньян')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'КНР', 'Пекин')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Кувейт', 'Эль-Кувейт')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Лаос', 'Вьентьян')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Ливан', 'Бейрут')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Малайзия', 'Куала-Лумпур')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Мальдивы', 'Мале')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Монголия', 'Улан-Батор')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Мьянма', 'Нейпьидо')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Непал', 'Катманду')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'ОАЭ', 'Абу-Даби')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Оман', 'Маскат')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Пакистан', 'Исламабад')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Республика Корея', 'Сеул')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Саудовская Аравия', 'Эр-Рияд')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Сингапур', 'Сингапур')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Сирия', 'Дамаск')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Таджикистан', 'Душанбе')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Таиланд', 'Бангкок')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Туркмения', 'Ашхабад')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Турция', 'Анкара')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Узбекистан', 'Ташкент')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Филиппины', 'Манила')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Шри-Ланка', 'Шри-Джаяварденепура-Котте')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Азия', 'Япония', 'Токио')

INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Алжир', 'Алжир')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Ангола', 'Луанда')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Бенин', 'Порто-Ново')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Ботсвана', 'Габороне')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Буркина-Фасо', 'Уагадугу')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Бурунди', 'Бужумбура')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Габон', 'Либревиль')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Гамбия', 'Банжул')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Гана', 'Аккра')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Гвинея-Бисау', 'Бисау')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Гвинея', 'Конакри')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Джибути', 'Джибути')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'ДР Конго', 'Киншаса')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Египет', 'Каир')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Замбия', 'Лусака')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Зимбабве', 'Хараре')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Кабо-Верде', 'Прая')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Камерун', 'Яунде')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Кения', 'Найроби')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Коморы', 'Морони')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Кот-д’Ивуар', 'Ямусукро')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Лесото', 'Масеру')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Либерия', 'Монровия')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Маврикий', 'Порт-Луи')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Мавритания', 'Нуакшот')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Мадагаскар', 'Антананариву')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Малави', 'Лилонгве')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Мали', 'Бамако')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Марокко', 'Рабат')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Мозамбик', 'Мапуту')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Намибия', 'Виндхук')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Нигер', 'Ниамей')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Нигерия', 'Абуджа')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Республика Конго', 'Браззавиль')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Руанда', 'Кигали')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Сан-Томе и Принсипи', 'Сан-Томе')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Свазиленд', 'Мбабане')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Сейшельские Острова', 'Виктория')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Сенегал', 'Дакар')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Сомали', 'Могадишо')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Судан', 'Хартум')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Сьерра-Леоне', 'Фритаун')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Танзания', 'Додома')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Того', 'Ломе')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Тунис', 'Тунис')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Уганда', 'Кампала')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Ливия', 'Триполи')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'ЦАР', 'Банги')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Чад', 'Нджамена')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Экваториальная Гвинея', 'Малабо')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Эритрея', 'Асмэра')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Эфиопия', 'Аддис-Абеба')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'ЮАР', 'Претория')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Африка', 'Южный Судан', 'Джуба')

INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Антигуа и Барбуда', 'Сент-Джонс')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Аргентина', 'Буэнос-Айрес')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Багамы', 'Нассау')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Барбадос', 'Бриджтаун')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Белиз', 'Бельмопан')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Боливия', 'Сукре')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Бразилия', 'Бразилиа')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Венесуэла', 'Каракас')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Гаити', 'Порт-о-Пренс')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Гайана', 'Джорджтаун')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Гватемала', 'Гватемала')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Гвиана', 'Кайенна')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Гондурас', 'Тегусигальпа')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Гренада', 'Сент-Джорджес')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Доминика', 'Розо')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Доминиканская Республика', 'Санто-Доминго')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Канада', 'Оттава')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Колумбия', 'Богота')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Коста-Рика', 'Сан-Хосе')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Куба', 'Гавана')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Мексика', 'Мехико')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Никарагуа', 'Манагуа')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Панама', 'Панама')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Парагвай', 'Асунсьон')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Перу', 'Лима')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Сальвадор', 'Сан-Сальвадор')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Сент-Винсент и Гренадины', 'Кингстаун')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Сент-Китс и Невис', 'Бастер')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Сент-Люсия', 'Кастри')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Суринам', 'Парамарибо')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'США', 'Вашингтон')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Тринидад и Тобаго', 'Порт-оф-Спейн')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Уругвай', 'Монтевидео')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Чили', 'Сантьяго')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Эквадор', 'Кито')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Америка', 'Ямайка', 'Кингстон')

INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Австралия', 'Канберра')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Вануату', 'Порт-Вила')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Кирибати', 'Южная Тарава (Баирики)')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Маршалловы Острова', 'Маджуро')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Микронезия', 'Паликир')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Новая Зеландия', 'Веллингтон')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Палау', 'Нгерулмуд')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Папуа — Новая Гвинея', 'Порт-Морсби')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Самоа', 'Апиа')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Соломоновы Острова', 'Хониара')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Тонга', 'Нукуалофа')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Тувалу', 'Фунафути')
INSERT INTO CountryCapital (PartOfWorld, Country, CapitalCity) VALUES ('Австралия и Океания', 'Фиджи', 'Сува')

SELECT * FROM CountryCapital

/*
USE master
DROP DATABASE BelhardTraining
*/
