using System;
using System.Collections.Generic;
using System.Globalization;

namespace TrainingCenter.Globalization
{
    // TODO: Some languages have two unique ISO three-letter codes
    public class LanguageInfo
    {
        static Lazy<Dictionary<string, LanguageInfo>> ThreeLetterIsoToLanguage = new Lazy<Dictionary<string, LanguageInfo>>(GetThreeLetterIsoToLanguage);
        static Lazy<Dictionary<string, LanguageInfo>> TwoLetterIsoToLanguage = new Lazy<Dictionary<string, LanguageInfo>>(GetTwoLetterIsoToLanguage);

        static Dictionary<string, LanguageInfo> GetTwoLetterIsoToLanguage()
        {
            return new Dictionary<string, LanguageInfo>
            {
            };
        }

        static Dictionary<string, LanguageInfo> GetThreeLetterIsoToLanguage()
        {
            return new Dictionary<string, LanguageInfo>
            {
                {"aar", new LanguageInfo("Afar", "aa", "aar", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"aav", new LanguageInfo("Austro-Asiatic languages", "", "aav", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"abk", new LanguageInfo("Abkhazian", "ab", "abk", LanguageFamily.NorthwestCaucasian, LanguageType.Living) },
                {"ace", new LanguageInfo("Achinese", "", "ace", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ach", new LanguageInfo("Acoli", "", "ach", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ada", new LanguageInfo("Adangme", "", "ada", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ady", new LanguageInfo("Adyghe", "", "ady", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"afa", new LanguageInfo("AfroAsiatic languages", "", "afa", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"afh", new LanguageInfo("Afrihili", "", "afh", LanguageFamily.NotSpecified, LanguageType.Constructed) },
                {"afr", new LanguageInfo("Afrikaans", "af", "afr", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ain", new LanguageInfo("Ainu (Japan)", "", "ain", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"aka", new LanguageInfo("Akan", "ak", "aka", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"akk", new LanguageInfo("Akkadian", "", "akk", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"alb", new LanguageInfo("Albanian", "sq", "alb", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ale", new LanguageInfo("Aleut", "", "ale", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"alg", new LanguageInfo("Algonquian languages", "", "alg", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"alt", new LanguageInfo("Southern Altai", "", "alt", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"alv", new LanguageInfo("Atlantic-Congo languages", "", "alv", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"amh", new LanguageInfo("Amharic", "am", "amh", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"ang", new LanguageInfo("Old English (ca. 450-1100)", "", "ang", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"anp", new LanguageInfo("Angika", "", "anp", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"apa", new LanguageInfo("Apache languages", "", "apa", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"aqa", new LanguageInfo("Alacalufan languages", "", "aqa", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"aql", new LanguageInfo("Algic languages", "", "aql", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ara", new LanguageInfo("Arabic", "ar", "ara", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"arc", new LanguageInfo("Official Aramaic (700-300 BCE)", "", "arc", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"arg", new LanguageInfo("Aragonese", "an", "arg", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"arm", new LanguageInfo("Armenian", "hy", "arm", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"arn", new LanguageInfo("Mapudungun", "", "arn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"arp", new LanguageInfo("Arapaho", "", "arp", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"art", new LanguageInfo("Artificial languages", "", "art", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"arw", new LanguageInfo("Arawak", "", "arw", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"asm", new LanguageInfo("Assamese", "as", "asm", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ast", new LanguageInfo("Asturian", "", "ast", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ath", new LanguageInfo("Athapascan languages", "", "ath", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"auf", new LanguageInfo("Arauan languages", "", "auf", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"aus", new LanguageInfo("Australian languages", "", "aus", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ava", new LanguageInfo("Avaric", "av", "ava", LanguageFamily.NortheastCaucasian, LanguageType.Living) },
                {"ave", new LanguageInfo("Avestan", "ae", "ave", LanguageFamily.IndoEuropean, LanguageType.Ancient) },
                {"awa", new LanguageInfo("Awadhi", "", "awa", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"awd", new LanguageInfo("Arawakan languages", "", "awd", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"aym", new LanguageInfo("Aymara", "ay", "aym", LanguageFamily.Aymaran, LanguageType.Living) },
                {"azc", new LanguageInfo("Uto-Aztecan languages", "", "azc", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"aze", new LanguageInfo("Azerbaijani", "az", "aze", LanguageFamily.Turkic, LanguageType.Living) },
                {"bad", new LanguageInfo("Banda languages", "", "bad", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"bai", new LanguageInfo("Bamileke languages", "", "bai", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"bak", new LanguageInfo("Bashkir", "ba", "bak", LanguageFamily.Turkic, LanguageType.Living) },
                {"bal", new LanguageInfo("Baluchi", "", "bal", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bam", new LanguageInfo("Bambara", "bm", "bam", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"ban", new LanguageInfo("Balinese", "", "ban", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"baq", new LanguageInfo("Basque", "eu", "baq", LanguageFamily.LanguageIsolate, LanguageType.Living) },
                {"bas", new LanguageInfo("Basa (Cameroon)", "", "bas", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bat", new LanguageInfo("Baltic languages", "", "bat", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"bej", new LanguageInfo("Beja", "", "bej", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bel", new LanguageInfo("Belarusian", "be", "bel", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"bem", new LanguageInfo("Bemba (Zambia)", "", "bem", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ben", new LanguageInfo("Bengali", "bn", "ben", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ber", new LanguageInfo("Berber languages", "", "ber", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"bho", new LanguageInfo("Bhojpuri", "", "bho", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bih", new LanguageInfo("Bihari languages", "bh", "bih", LanguageFamily.IndoEuropean, LanguageType.NotSpecified) },
                {"bik", new LanguageInfo("Bikol", "", "bik", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bin", new LanguageInfo("Bini", "", "bin", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bis", new LanguageInfo("Bislama", "bi", "bis", LanguageFamily.Creole, LanguageType.Living) },
                {"bla", new LanguageInfo("Siksika", "", "bla", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bnt", new LanguageInfo("Bantu languages", "", "bnt", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"bod", new LanguageInfo("Tibetan", "bo", "bod", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"bos", new LanguageInfo("Bosnian", "bs", "bos", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"bra", new LanguageInfo("Braj", "", "bra", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bre", new LanguageInfo("Breton", "br", "bre", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"btk", new LanguageInfo("Batak languages", "", "btk", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"bua", new LanguageInfo("Buriat", "", "bua", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bug", new LanguageInfo("Buginese", "", "bug", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"bul", new LanguageInfo("Bulgarian", "bg", "bul", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"bur", new LanguageInfo("Burmese", "my", "bur", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"byn", new LanguageInfo("Bilin", "", "byn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"cad", new LanguageInfo("Caddo", "", "cad", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"cai", new LanguageInfo("Central American Indian languages", "", "cai", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"car", new LanguageInfo("Galibi Carib", "", "car", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"cat", new LanguageInfo("Catalan", "ca", "cat", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"cau", new LanguageInfo("Caucasian languages", "", "cau", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cba", new LanguageInfo("Chibchan languages", "", "cba", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ccn", new LanguageInfo("North Caucasian languages", "", "ccn", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ccs", new LanguageInfo("South Caucasian languages", "", "ccs", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cdc", new LanguageInfo("Chadic languages", "", "cdc", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cdd", new LanguageInfo("Caddoan languages", "", "cdd", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ceb", new LanguageInfo("Cebuano", "", "ceb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"cel", new LanguageInfo("Celtic languages", "", "cel", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ces", new LanguageInfo("Czech", "cs", "ces", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"cha", new LanguageInfo("Chamorro", "ch", "cha", LanguageFamily.Austronesian, LanguageType.Living) },
                {"chb", new LanguageInfo("Chibcha", "", "chb", LanguageFamily.NotSpecified, LanguageType.Extinct) },
                {"che", new LanguageInfo("Chechen", "ce", "che", LanguageFamily.NortheastCaucasian, LanguageType.Living) },
                {"chg", new LanguageInfo("Chagatai", "", "chg", LanguageFamily.NotSpecified, LanguageType.Extinct) },
                {"chi", new LanguageInfo("Chinese", "zh", "chi", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"chk", new LanguageInfo("Chuukese", "", "chk", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"chm", new LanguageInfo("Mari (Russia)", "", "chm", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"chn", new LanguageInfo("Chinook jargon", "", "chn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"cho", new LanguageInfo("Choctaw", "", "cho", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"chp", new LanguageInfo("Chipewyan", "", "chp", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"chr", new LanguageInfo("Cherokee", "", "chr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"chu", new LanguageInfo("Church Slavic", "cu", "chu", LanguageFamily.IndoEuropean, LanguageType.Ancient) },
                {"chv", new LanguageInfo("Chuvash", "cv", "chv", LanguageFamily.Turkic, LanguageType.Living) },
                {"chy", new LanguageInfo("Cheyenne", "", "chy", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"cmc", new LanguageInfo("Chamic languages", "", "cmc", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cop", new LanguageInfo("Coptic", "", "cop", LanguageFamily.NotSpecified, LanguageType.Extinct) },
                {"cor", new LanguageInfo("Cornish", "kw", "cor", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"cos", new LanguageInfo("Corsican", "co", "cos", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"cpe", new LanguageInfo("English based Creoles and pidgins", "", "cpe", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cpf", new LanguageInfo("French-Based Creoles and pidgins", "", "cpf", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cpp", new LanguageInfo("Portuguese-Based Creoles and pidgins", "", "cpp", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cre", new LanguageInfo("Cree", "cr", "cre", LanguageFamily.Algonquian, LanguageType.Living) },
                {"crh", new LanguageInfo("Crimean Tatar", "", "crh", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"crp", new LanguageInfo("Creoles and pidgins", "", "crp", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"csb", new LanguageInfo("Kashubian", "", "csb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"csu", new LanguageInfo("Central Sudanic languages", "", "csu", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cus", new LanguageInfo("Cushitic languages", "", "cus", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"cym", new LanguageInfo("Welsh", "cy", "cym", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"cze", new LanguageInfo("Czech", "cs", "cze", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"dak", new LanguageInfo("Dakota", "", "dak", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"dan", new LanguageInfo("Danish", "da", "dan", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"dar", new LanguageInfo("Dargwa", "", "dar", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"day", new LanguageInfo("Land Dayak languages", "", "day", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"del", new LanguageInfo("Delaware", "", "del", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"den", new LanguageInfo("Slave (Athapascan)", "", "den", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"deu", new LanguageInfo("German", "de", "deu", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"dgr", new LanguageInfo("Dogrib", "", "dgr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"din", new LanguageInfo("Dinka", "", "din", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"div", new LanguageInfo("Dhivehi", "dv", "div", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"dmn", new LanguageInfo("Mande languages", "", "dmn", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"doi", new LanguageInfo("Dogri (macrolanguage)", "", "doi", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"dra", new LanguageInfo("Dravidian languages", "", "dra", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"dsb", new LanguageInfo("Lower Sorbian", "", "dsb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"dua", new LanguageInfo("Duala", "", "dua", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"dum", new LanguageInfo("Middle Dutch (ca. 1050-1350)", "", "dum", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"dut", new LanguageInfo("Dutch", "nl", "dut", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"dyu", new LanguageInfo("Dyula", "", "dyu", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"dzo", new LanguageInfo("Dzongkha", "dz", "dzo", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"efi", new LanguageInfo("Efik", "", "efi", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"egx", new LanguageInfo("Egyptian languages", "", "egx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"egy", new LanguageInfo("Egyptian (Ancient)", "", "egy", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"eka", new LanguageInfo("Ekajuk", "", "eka", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ell", new LanguageInfo("Modern Greek (1453-)", "el", "ell", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"elx", new LanguageInfo("Elamite", "", "elx", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"eng", new LanguageInfo("English", "en", "eng", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"enm", new LanguageInfo("Middle English (1100-1500)", "", "enm", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"epo", new LanguageInfo("Esperanto", "eo", "epo", LanguageFamily.Constructed, LanguageType.Constructed) },
                {"est", new LanguageInfo("Estonian", "et", "est", LanguageFamily.Uralic, LanguageType.Living) },
                {"esx", new LanguageInfo("Eskimo-Aleut languages", "", "esx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"euq", new LanguageInfo("Basque (family)", "", "euq", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"eus", new LanguageInfo("Basque", "eu", "eus", LanguageFamily.LanguageIsolate, LanguageType.Living) },
                {"ewe", new LanguageInfo("Ewe", "ee", "ewe", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"ewo", new LanguageInfo("Ewondo", "", "ewo", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"fan", new LanguageInfo("Fang (Equatorial Guinea)", "", "fan", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"fao", new LanguageInfo("Faroese", "fo", "fao", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"fas", new LanguageInfo("Persian", "fa", "fas", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"fat", new LanguageInfo("Fanti", "", "fat", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"fij", new LanguageInfo("Fijian", "fj", "fij", LanguageFamily.Austronesian, LanguageType.Living) },
                {"fil", new LanguageInfo("Filipino", "", "fil", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"fin", new LanguageInfo("Finnish", "fi", "fin", LanguageFamily.Uralic, LanguageType.Living) },
                {"fiu", new LanguageInfo("Finno-Ugrian languages", "", "fiu", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"fon", new LanguageInfo("Fon", "", "fon", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"fox", new LanguageInfo("Formosan languages", "", "fox", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"fra", new LanguageInfo("French", "fr", "fra", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"fre", new LanguageInfo("French", "fr", "fre", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"frm", new LanguageInfo("Middle French (ca. 1400-1600)", "", "frm", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"fro", new LanguageInfo("Old French (842-ca. 1400)", "", "fro", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"frr", new LanguageInfo("Northern Frisian", "", "frr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"frs", new LanguageInfo("Eastern Frisian", "", "frs", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"fry", new LanguageInfo("Western Frisian", "fy", "fry", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ful", new LanguageInfo("Fulah", "ff", "ful", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"fur", new LanguageInfo("Friulian", "", "fur", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"gaa", new LanguageInfo("Ga", "", "gaa", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"gay", new LanguageInfo("Gayo", "", "gay", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"gba", new LanguageInfo("Gbaya (Central African Republic)", "", "gba", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"gem", new LanguageInfo("Germanic languages", "", "gem", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"geo", new LanguageInfo("Georgian", "ka", "geo", LanguageFamily.SouthCaucasian, LanguageType.Living) },
                {"ger", new LanguageInfo("German", "de", "ger", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"gez", new LanguageInfo("Geez", "", "gez", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"gil", new LanguageInfo("Gilbertese", "", "gil", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"gla", new LanguageInfo("Scottish Gaelic", "gd", "gla", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"gle", new LanguageInfo("Irish", "ga", "gle", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"glg", new LanguageInfo("Galician", "gl", "glg", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"glv", new LanguageInfo("Manx", "gv", "glv", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"gme", new LanguageInfo("East Germanic languages", "", "gme", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"gmh", new LanguageInfo("Middle High German (ca. 1050-1500)", "", "gmh", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"gmq", new LanguageInfo("North Germanic languages", "", "gmq", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"gmw", new LanguageInfo("West Germanic languages", "", "gmw", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"goh", new LanguageInfo("Old High German (ca. 750-1050)", "", "goh", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"gon", new LanguageInfo("Gondi", "", "gon", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"gor", new LanguageInfo("Gorontalo", "", "gor", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"got", new LanguageInfo("Gothic", "", "got", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"grb", new LanguageInfo("Grebo", "", "grb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"grc", new LanguageInfo("Ancient Greek (to 1453)", "", "grc", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"gre", new LanguageInfo("Modern Greek (1453-)", "el", "gre", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"grk", new LanguageInfo("Greek languages", "", "grk", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"grn", new LanguageInfo("Guarani", "gn", "grn", LanguageFamily.Tupian, LanguageType.Living) },
                {"gsw", new LanguageInfo("Swiss German", "", "gsw", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"guj", new LanguageInfo("Gujarati", "gu", "guj", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"gwi", new LanguageInfo("Gwichʼin", "", "gwi", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"hai", new LanguageInfo("Haida", "", "hai", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"hat", new LanguageInfo("Haitian", "ht", "hat", LanguageFamily.Creole, LanguageType.Living) },
                {"hau", new LanguageInfo("Hausa", "ha", "hau", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"haw", new LanguageInfo("Hawaiian", "", "haw", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"heb", new LanguageInfo("Hebrew", "he", "heb", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"her", new LanguageInfo("Herero", "hz", "her", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"hil", new LanguageInfo("Hiligaynon", "", "hil", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"him", new LanguageInfo("Himachali languages", "", "him", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"hin", new LanguageInfo("Hindi", "hi", "hin", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"hit", new LanguageInfo("Hittite", "", "hit", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"hmn", new LanguageInfo("Hmong", "", "hmn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"hmo", new LanguageInfo("Hiri Motu", "ho", "hmo", LanguageFamily.Austronesian, LanguageType.Living) },
                {"hmx", new LanguageInfo("Hmong-Mien languages", "", "hmx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"hok", new LanguageInfo("Hokan languages", "", "hok", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"hrv", new LanguageInfo("Croatian", "hr", "hrv", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"hsb", new LanguageInfo("Upper Sorbian", "", "hsb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"hun", new LanguageInfo("Hungarian", "hu", "hun", LanguageFamily.Uralic, LanguageType.Living) },
                {"hup", new LanguageInfo("Hupa", "", "hup", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"hye", new LanguageInfo("Armenian", "hy", "hye", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"hyx", new LanguageInfo("Armenian (family)", "", "hyx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"iba", new LanguageInfo("Iban", "", "iba", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ibo", new LanguageInfo("Igbo", "ig", "ibo", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"ice", new LanguageInfo("Icelandic", "is", "ice", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ido", new LanguageInfo("Ido", "io", "ido", LanguageFamily.Constructed, LanguageType.Constructed) },
                {"iii", new LanguageInfo("Sichuan Yi", "ii", "iii", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"iir", new LanguageInfo("Indo-Iranian languages", "", "iir", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ijo", new LanguageInfo("Ijo languages", "", "ijo", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"iku", new LanguageInfo("Inuktitut", "iu", "iku", LanguageFamily.EskimoAleut, LanguageType.Living) },
                {"ile", new LanguageInfo("Interlingue", "ie", "ile", LanguageFamily.Constructed, LanguageType.Constructed) },
                {"ilo", new LanguageInfo("Iloko", "", "ilo", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ina", new LanguageInfo("Interlingua", "ia", "ina", LanguageFamily.Constructed, LanguageType.Constructed) },
                {"inc", new LanguageInfo("Indic languages", "", "inc", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ind", new LanguageInfo("Indonesian", "id", "ind", LanguageFamily.Austronesian, LanguageType.Living) },
                {"ine", new LanguageInfo("IndoEuropean languages", "", "ine", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"inh", new LanguageInfo("Ingush", "", "inh", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ipk", new LanguageInfo("Inupiaq", "ik", "ipk", LanguageFamily.EskimoAleut, LanguageType.Living) },
                {"ira", new LanguageInfo("Iranian languages", "", "ira", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"iro", new LanguageInfo("Iroquoian languages", "", "iro", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"isl", new LanguageInfo("Icelandic", "is", "isl", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ita", new LanguageInfo("Italian", "it", "ita", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"itc", new LanguageInfo("Italic languages", "", "itc", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"jav", new LanguageInfo("Javanese", "jv", "jav", LanguageFamily.Austronesian, LanguageType.Living) },
                {"jbo", new LanguageInfo("Lojban", "", "jbo", LanguageFamily.NotSpecified, LanguageType.Constructed) },
                {"jpn", new LanguageInfo("Japanese", "ja", "jpn", LanguageFamily.Japonic, LanguageType.Living) },
                {"jpr", new LanguageInfo("Judeo-Persian", "", "jpr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"jpx", new LanguageInfo("Japanese (family)", "", "jpx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"jrb", new LanguageInfo("Judeo-Arabic", "", "jrb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kaa", new LanguageInfo("Kara-Kalpak", "", "kaa", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kab", new LanguageInfo("Kabyle", "", "kab", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kac", new LanguageInfo("Kachin", "", "kac", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kal", new LanguageInfo("Kalaallisut", "kl", "kal", LanguageFamily.EskimoAleut, LanguageType.Living) },
                {"kam", new LanguageInfo("Kamba (Kenya)", "", "kam", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kan", new LanguageInfo("Kannada", "kn", "kan", LanguageFamily.Dravidian, LanguageType.Living) },
                {"kar", new LanguageInfo("Karen languages", "", "kar", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"kas", new LanguageInfo("Kashmiri", "ks", "kas", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"kat", new LanguageInfo("Georgian", "ka", "kat", LanguageFamily.SouthCaucasian, LanguageType.Living) },
                {"kau", new LanguageInfo("Kanuri", "kr", "kau", LanguageFamily.NiloSaharan, LanguageType.Living) },
                {"kaw", new LanguageInfo("Kawi", "", "kaw", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"kaz", new LanguageInfo("Kazakh", "kk", "kaz", LanguageFamily.Turkic, LanguageType.Living) },
                {"kbd", new LanguageInfo("Kabardian", "", "kbd", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kdo", new LanguageInfo("Kordofanian languages", "", "kdo", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"kha", new LanguageInfo("Khasi", "", "kha", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"khi", new LanguageInfo("Khoisan languages", "", "khi", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"khm", new LanguageInfo("Central Khmer", "km", "khm", LanguageFamily.Austroasiatic, LanguageType.Living) },
                {"kho", new LanguageInfo("Khotanese", "", "kho", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"kik", new LanguageInfo("Kikuyu", "ki", "kik", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"kin", new LanguageInfo("Kinyarwanda", "rw", "kin", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"kir", new LanguageInfo("Kirghiz", "ky", "kir", LanguageFamily.Turkic, LanguageType.Living) },
                {"kmb", new LanguageInfo("Kimbundu", "", "kmb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kok", new LanguageInfo("Konkani (macrolanguage)", "", "kok", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kom", new LanguageInfo("Komi", "kv", "kom", LanguageFamily.Uralic, LanguageType.Living) },
                {"kon", new LanguageInfo("Kongo", "kg", "kon", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"kor", new LanguageInfo("Korean", "ko", "kor", LanguageFamily.Koreanic, LanguageType.Living) },
                {"kos", new LanguageInfo("Kosraean", "", "kos", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kpe", new LanguageInfo("Kpelle", "", "kpe", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"krc", new LanguageInfo("Karachay-Balkar", "", "krc", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"krl", new LanguageInfo("Karelian", "", "krl", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kro", new LanguageInfo("Kru languages", "", "kro", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"kru", new LanguageInfo("Kurukh", "", "kru", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kua", new LanguageInfo("Kuanyama", "kj", "kua", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"kum", new LanguageInfo("Kumyk", "", "kum", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"kur", new LanguageInfo("Kurdish", "ku", "kur", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"kut", new LanguageInfo("Kutenai", "", "kut", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lad", new LanguageInfo("Ladino", "", "lad", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lah", new LanguageInfo("Lahnda", "", "lah", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lam", new LanguageInfo("Lamba", "", "lam", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lao", new LanguageInfo("Lao", "lo", "lao", LanguageFamily.TaiKadai, LanguageType.Living) },
                {"lat", new LanguageInfo("Latin", "la", "lat", LanguageFamily.IndoEuropean, LanguageType.Ancient) },
                {"lav", new LanguageInfo("Latvian", "lv", "lav", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"lez", new LanguageInfo("Lezghian", "", "lez", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lim", new LanguageInfo("Limburgan", "li", "lim", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"lin", new LanguageInfo("Lingala", "ln", "lin", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"lit", new LanguageInfo("Lithuanian", "lt", "lit", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"lol", new LanguageInfo("Mongo", "", "lol", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"loz", new LanguageInfo("Lozi", "", "loz", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ltz", new LanguageInfo("Luxembourgish", "lb", "ltz", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"lua", new LanguageInfo("Luba-Lulua", "", "lua", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lub", new LanguageInfo("Luba-Katanga", "lu", "lub", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"lug", new LanguageInfo("Ganda", "lg", "lug", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"lui", new LanguageInfo("Luiseno", "", "lui", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lun", new LanguageInfo("Lunda", "", "lun", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"luo", new LanguageInfo("Luo (Kenya and Tanzania)", "", "luo", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"lus", new LanguageInfo("Lushai", "", "lus", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mac", new LanguageInfo("Macedonian", "mk", "mac", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"mad", new LanguageInfo("Madurese", "", "mad", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mag", new LanguageInfo("Magahi", "", "mag", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mah", new LanguageInfo("Marshallese", "mh", "mah", LanguageFamily.Austronesian, LanguageType.Living) },
                {"mai", new LanguageInfo("Maithili", "", "mai", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mak", new LanguageInfo("Makasar", "", "mak", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mal", new LanguageInfo("Malayalam", "ml", "mal", LanguageFamily.Dravidian, LanguageType.Living) },
                {"man", new LanguageInfo("Mandingo", "", "man", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mao", new LanguageInfo("Maori", "mi", "mao", LanguageFamily.Austronesian, LanguageType.Living) },
                {"map", new LanguageInfo("Austronesian languages", "", "map", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"mar", new LanguageInfo("Marathi", "mr", "mar", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"mas", new LanguageInfo("Masai", "", "mas", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"may", new LanguageInfo("Malay (macrolanguage)", "ms", "may", LanguageFamily.Austronesian, LanguageType.Living) },
                {"mdf", new LanguageInfo("Moksha", "", "mdf", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mdr", new LanguageInfo("Mandar", "", "mdr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"men", new LanguageInfo("Mende (Sierra Leone)", "", "men", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mga", new LanguageInfo("Middle Irish (900-1200)", "", "mga", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"mic", new LanguageInfo("Mi'kmaq", "", "mic", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"min", new LanguageInfo("Minangkabau", "", "min", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mis", new LanguageInfo("Uncoded languages", "", "mis", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"mkd", new LanguageInfo("Macedonian", "mk", "mkd", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"mkh", new LanguageInfo("Mon-Khmer languages", "", "mkh", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"mlg", new LanguageInfo("Malagasy", "mg", "mlg", LanguageFamily.Austronesian, LanguageType.Living) },
                {"mlt", new LanguageInfo("Maltese", "mt", "mlt", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"mnc", new LanguageInfo("Manchu", "", "mnc", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mni", new LanguageInfo("Manipuri", "", "mni", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mno", new LanguageInfo("Manobo languages", "", "mno", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"moh", new LanguageInfo("Mohawk", "", "moh", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mon", new LanguageInfo("Mongolian", "mn", "mon", LanguageFamily.Mongolic, LanguageType.Living) },
                {"mos", new LanguageInfo("Mossi", "", "mos", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mri", new LanguageInfo("Maori", "mi", "mri", LanguageFamily.Austronesian, LanguageType.Living) },
                {"msa", new LanguageInfo("Malay (macrolanguage)", "ms", "msa", LanguageFamily.Austronesian, LanguageType.Living) },
                {"mul", new LanguageInfo("Multiple languages", "", "mul", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"mun", new LanguageInfo("Munda languages", "", "mun", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"mus", new LanguageInfo("Creek", "", "mus", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mwl", new LanguageInfo("Mirandese", "", "mwl", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mwr", new LanguageInfo("Marwari", "", "mwr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"mya", new LanguageInfo("Burmese", "my", "mya", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"myn", new LanguageInfo("Mayan languages", "", "myn", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"myv", new LanguageInfo("Erzya", "", "myv", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nah", new LanguageInfo("Nahuatl languages", "", "nah", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"nai", new LanguageInfo("North American Indian", "", "nai", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"nap", new LanguageInfo("Neapolitan", "", "nap", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nau", new LanguageInfo("Nauru", "na", "nau", LanguageFamily.Austronesian, LanguageType.Living) },
                {"nav", new LanguageInfo("Navajo", "nv", "nav", LanguageFamily.DeneYeniseian, LanguageType.Living) },
                {"nbl", new LanguageInfo("South Ndebele", "nr", "nbl", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"nde", new LanguageInfo("North Ndebele", "nd", "nde", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"ndo", new LanguageInfo("Ndonga", "ng", "ndo", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"nds", new LanguageInfo("Low German", "", "nds", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nep", new LanguageInfo("Nepali (macrolanguage)", "ne", "nep", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"new", new LanguageInfo("Nepal Bhasa", "", "new", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ngf", new LanguageInfo("Trans-New Guinea languages", "", "ngf", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"nia", new LanguageInfo("Nias", "", "nia", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nic", new LanguageInfo("Niger-Kordofanian languages", "", "nic", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"niu", new LanguageInfo("Niuean", "", "niu", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nld", new LanguageInfo("Dutch", "nl", "nld", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"nno", new LanguageInfo("Norwegian Nynorsk", "nn", "nno", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"nob", new LanguageInfo("Norwegian Bokmål", "nb", "nob", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"nog", new LanguageInfo("Nogai", "", "nog", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"non", new LanguageInfo("Old Norse", "", "non", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"nor", new LanguageInfo("Norwegian", "no", "nor", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"nqo", new LanguageInfo("N'Ko", "", "nqo", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nso", new LanguageInfo("Pedi", "", "nso", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nub", new LanguageInfo("Nubian languages", "", "nub", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"nwc", new LanguageInfo("Classical Newari", "", "nwc", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"nya", new LanguageInfo("Nyanja", "ny", "nya", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"nym", new LanguageInfo("Nyamwezi", "", "nym", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nyn", new LanguageInfo("Nyankole", "", "nyn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nyo", new LanguageInfo("Nyoro", "", "nyo", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"nzi", new LanguageInfo("Nzima", "", "nzi", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"oci", new LanguageInfo("Occitan (post 1500)", "oc", "oci", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"oji", new LanguageInfo("Ojibwa", "oj", "oji", LanguageFamily.Algonquian, LanguageType.Living) },
                {"omq", new LanguageInfo("Oto-Manguean languages", "", "omq", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"omv", new LanguageInfo("Omotic languages", "", "omv", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ori", new LanguageInfo("Odiya (macrolanguage)", "or", "ori", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"orm", new LanguageInfo("Oromo", "om", "orm", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"osa", new LanguageInfo("Osage", "", "osa", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"oss", new LanguageInfo("Ossetian", "os", "oss", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"ota", new LanguageInfo("Ottoman Turkish (1500-1928)", "", "ota", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"oto", new LanguageInfo("Otomian languages", "", "oto", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"paa", new LanguageInfo("Papuan languages", "", "paa", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"pag", new LanguageInfo("Pangasinan", "", "pag", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"pal", new LanguageInfo("Pahlavi", "", "pal", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"pam", new LanguageInfo("Pampanga", "", "pam", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"pan", new LanguageInfo("Panjabi", "pa", "pan", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"pap", new LanguageInfo("Papiamento", "", "pap", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"pau", new LanguageInfo("Palauan", "", "pau", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"peo", new LanguageInfo("Old Persian (ca. 600-400 B.C.)", "", "peo", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"per", new LanguageInfo("Persian", "fa", "per", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"phi", new LanguageInfo("Philippine languages", "", "phi", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"phn", new LanguageInfo("Phoenician", "", "phn", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"plf", new LanguageInfo("Central Malayo-Polynesian languages", "", "plf", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"pli", new LanguageInfo("Pali", "pi", "pli", LanguageFamily.IndoEuropean, LanguageType.Ancient) },
                {"pol", new LanguageInfo("Polish", "pl", "pol", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"pon", new LanguageInfo("Pohnpeian", "", "pon", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"por", new LanguageInfo("Portuguese", "pt", "por", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"poz", new LanguageInfo("Malayo-Polynesian languages", "", "poz", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"pqe", new LanguageInfo("Eastern Malayo-Polynesian languages", "", "pqe", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"pqw", new LanguageInfo("Western Malayo-Polynesian languages", "", "pqw", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"pra", new LanguageInfo("Prakrit languages", "", "pra", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"pro", new LanguageInfo("Old Provençal (to 1500)", "", "pro", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"pus", new LanguageInfo("Pushto", "ps", "pus", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"qaa-qtz", new LanguageInfo("Reserved for local use", "", "qaa-qtz", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"que", new LanguageInfo("Quechua", "qu", "que", LanguageFamily.Quechuan, LanguageType.Living) },
                {"qwe", new LanguageInfo("Quechuan (family)", "", "qwe", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"raj", new LanguageInfo("Rajasthani", "", "raj", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"rap", new LanguageInfo("Rapanui", "", "rap", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"rar", new LanguageInfo("Rarotongan", "", "rar", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"roa", new LanguageInfo("Romance languages", "", "roa", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"roh", new LanguageInfo("Romansh", "rm", "roh", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"rom", new LanguageInfo("Romany", "", "rom", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ron", new LanguageInfo("Romanian", "ro", "ron", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"rum", new LanguageInfo("Romanian", "ro", "rum", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"run", new LanguageInfo("Rundi", "rn", "run", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"rup", new LanguageInfo("Macedo-Romanian", "", "rup", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"rus", new LanguageInfo("Russian", "ru", "rus", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"sad", new LanguageInfo("Sandawe", "", "sad", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sag", new LanguageInfo("Sango", "sg", "sag", LanguageFamily.Creole, LanguageType.Living) },
                {"sah", new LanguageInfo("Yakut", "", "sah", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sai", new LanguageInfo("South American Indian languages", "", "sai", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sal", new LanguageInfo("Salishan languages", "", "sal", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sam", new LanguageInfo("Samaritan Aramaic", "", "sam", LanguageFamily.NotSpecified, LanguageType.Extinct) },
                {"san", new LanguageInfo("Sanskrit", "sa", "san", LanguageFamily.IndoEuropean, LanguageType.Ancient) },
                {"sas", new LanguageInfo("Sasak", "", "sas", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sat", new LanguageInfo("Santali", "", "sat", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"scn", new LanguageInfo("Sicilian", "", "scn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sco", new LanguageInfo("Scots", "", "sco", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sdv", new LanguageInfo("Eastern Sudanic languages", "", "sdv", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sel", new LanguageInfo("Selkup", "", "sel", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sem", new LanguageInfo("Semitic languages", "", "sem", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sga", new LanguageInfo("Old Irish (to 900)", "", "sga", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"sgn", new LanguageInfo("Sign languages", "", "sgn", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"shn", new LanguageInfo("Shan", "", "shn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sid", new LanguageInfo("Sidamo", "", "sid", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sin", new LanguageInfo("Sinhala", "si", "sin", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"sio", new LanguageInfo("Siouan languages", "", "sio", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sit", new LanguageInfo("SinoTibetan languages", "", "sit", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sla", new LanguageInfo("Slavic languages", "", "sla", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"slk", new LanguageInfo("Slovak", "sk", "slk", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"slo", new LanguageInfo("Slovak", "sk", "slo", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"slv", new LanguageInfo("Slovenian", "sl", "slv", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"sma", new LanguageInfo("Southern Sami", "", "sma", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sme", new LanguageInfo("Northern Sami", "se", "sme", LanguageFamily.Uralic, LanguageType.Living) },
                {"smi", new LanguageInfo("Sami languages", "", "smi", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"smj", new LanguageInfo("Lule Sami", "", "smj", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"smn", new LanguageInfo("Inari Sami", "", "smn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"smo", new LanguageInfo("Samoan", "sm", "smo", LanguageFamily.Austronesian, LanguageType.Living) },
                {"sms", new LanguageInfo("Skolt Sami", "", "sms", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sna", new LanguageInfo("Shona", "sn", "sna", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"snd", new LanguageInfo("Sindhi", "sd", "snd", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"snk", new LanguageInfo("Soninke", "", "snk", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sog", new LanguageInfo("Sogdian", "", "sog", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"som", new LanguageInfo("Somali", "so", "som", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"son", new LanguageInfo("Songhai languages", "", "son", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"sot", new LanguageInfo("Southern Sotho", "st", "sot", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"spa", new LanguageInfo("Spanish", "es", "spa", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"sqi", new LanguageInfo("Albanian", "sq", "sqi", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"srd", new LanguageInfo("Sardinian", "sc", "srd", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"srn", new LanguageInfo("Sranan Tongo", "", "srn", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"srp", new LanguageInfo("Serbian", "sr", "srp", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"srr", new LanguageInfo("Serer", "", "srr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ssa", new LanguageInfo("NiloSaharan languages", "", "ssa", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"ssw", new LanguageInfo("Swati", "ss", "ssw", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"suk", new LanguageInfo("Sukuma", "", "suk", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sun", new LanguageInfo("Sundanese", "su", "sun", LanguageFamily.Austronesian, LanguageType.Living) },
                {"sus", new LanguageInfo("Susu", "", "sus", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"sux", new LanguageInfo("Sumerian", "", "sux", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"swa", new LanguageInfo("Swahili (macrolanguage)", "sw", "swa", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"swe", new LanguageInfo("Swedish", "sv", "swe", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"syc", new LanguageInfo("Classical Syriac", "", "syc", LanguageFamily.NotSpecified, LanguageType.Historical) },
                {"syd", new LanguageInfo("Samoyedic languages", "", "syd", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"syr", new LanguageInfo("Syriac", "", "syr", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tah", new LanguageInfo("Tahitian", "ty", "tah", LanguageFamily.Austronesian, LanguageType.Living) },
                {"tai", new LanguageInfo("Tai languages", "", "tai", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"tam", new LanguageInfo("Tamil", "ta", "tam", LanguageFamily.Dravidian, LanguageType.Living) },
                {"tat", new LanguageInfo("Tatar", "tt", "tat", LanguageFamily.Turkic, LanguageType.Living) },
                {"tbq", new LanguageInfo("Tibeto-Burman languages", "", "tbq", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"tel", new LanguageInfo("Telugu", "te", "tel", LanguageFamily.Dravidian, LanguageType.Living) },
                {"tem", new LanguageInfo("Timne", "", "tem", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ter", new LanguageInfo("Tereno", "", "ter", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tet", new LanguageInfo("Tetum", "", "tet", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tgk", new LanguageInfo("Tajik", "tg", "tgk", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"tgl", new LanguageInfo("Tagalog", "tl", "tgl", LanguageFamily.Austronesian, LanguageType.Living) },
                {"tha", new LanguageInfo("Thai", "th", "tha", LanguageFamily.TaiKadai, LanguageType.Living) },
                {"tib", new LanguageInfo("Tibetan", "bo", "tib", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"tig", new LanguageInfo("Tigre", "", "tig", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tir", new LanguageInfo("Tigrinya", "ti", "tir", LanguageFamily.AfroAsiatic, LanguageType.Living) },
                {"tiv", new LanguageInfo("Tiv", "", "tiv", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tkl", new LanguageInfo("Tokelau", "", "tkl", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tlh", new LanguageInfo("Klingon", "", "tlh", LanguageFamily.NotSpecified, LanguageType.Constructed) },
                {"tli", new LanguageInfo("Tlingit", "", "tli", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tmh", new LanguageInfo("Tamashek", "", "tmh", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tog", new LanguageInfo("Tonga (Nyasa)", "", "tog", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ton", new LanguageInfo("Tonga (Tonga Islands)", "to", "ton", LanguageFamily.Austronesian, LanguageType.Living) },
                {"tpi", new LanguageInfo("Tok Pisin", "", "tpi", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"trk", new LanguageInfo("Turkic languages", "", "trk", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"tsi", new LanguageInfo("Tsimshian", "", "tsi", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tsn", new LanguageInfo("Tswana", "tn", "tsn", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"tso", new LanguageInfo("Tsonga", "ts", "tso", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"tuk", new LanguageInfo("Turkmen", "tk", "tuk", LanguageFamily.Turkic, LanguageType.Living) },
                {"tum", new LanguageInfo("Tumbuka", "", "tum", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"tup", new LanguageInfo("Tupi languages", "", "tup", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"tur", new LanguageInfo("Turkish", "tr", "tur", LanguageFamily.Turkic, LanguageType.Living) },
                {"tut", new LanguageInfo("Altaic languages", "", "tut", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"tuw", new LanguageInfo("Tungus languages", "", "tuw", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"tvl", new LanguageInfo("Tuvaluan", "", "tvl", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"twi", new LanguageInfo("Twi", "tw", "twi", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"tyv", new LanguageInfo("Tuvinian", "", "tyv", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"udm", new LanguageInfo("Udmurt", "", "udm", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"uga", new LanguageInfo("Ugaritic", "", "uga", LanguageFamily.NotSpecified, LanguageType.Ancient) },
                {"uig", new LanguageInfo("Uighur", "ug", "uig", LanguageFamily.Turkic, LanguageType.Living) },
                {"ukr", new LanguageInfo("Ukrainian", "uk", "ukr", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"umb", new LanguageInfo("Umbundu", "", "umb", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"und", new LanguageInfo("Undetermined", "", "und", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"urd", new LanguageInfo("Urdu", "ur", "urd", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"urj", new LanguageInfo("Uralic languages", "", "urj", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"uzb", new LanguageInfo("Uzbek", "uz", "uzb", LanguageFamily.Turkic, LanguageType.Living) },
                {"vai", new LanguageInfo("Vai", "", "vai", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"ven", new LanguageInfo("Venda", "ve", "ven", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"vie", new LanguageInfo("Vietnamese", "vi", "vie", LanguageFamily.Austroasiatic, LanguageType.Living) },
                {"vol", new LanguageInfo("Volapük", "vo", "vol", LanguageFamily.Constructed, LanguageType.Constructed) },
                {"vot", new LanguageInfo("Votic", "", "vot", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"wak", new LanguageInfo("Wakashan languages", "", "wak", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"wal", new LanguageInfo("Wolaytta", "", "wal", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"war", new LanguageInfo("Waray (Philippines)", "", "war", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"was", new LanguageInfo("Washo", "", "was", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"wel", new LanguageInfo("Welsh", "cy", "wel", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"wen", new LanguageInfo("Sorbian languages", "", "wen", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"wln", new LanguageInfo("Walloon", "wa", "wln", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"wol", new LanguageInfo("Wolof", "wo", "wol", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"xal", new LanguageInfo("Kalmyk", "", "xal", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"xgn", new LanguageInfo("Mongolian languages", "", "xgn", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"xho", new LanguageInfo("Xhosa", "xh", "xho", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"xnd", new LanguageInfo("Na-Dene languages", "", "xnd", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"yao", new LanguageInfo("Yao", "", "yao", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"yap", new LanguageInfo("Yapese", "", "yap", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"yid", new LanguageInfo("Yiddish", "yi", "yid", LanguageFamily.IndoEuropean, LanguageType.Living) },
                {"yor", new LanguageInfo("Yoruba", "yo", "yor", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"ypk", new LanguageInfo("Yupik languages", "", "ypk", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"zap", new LanguageInfo("Zapotec", "", "zap", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"zbl", new LanguageInfo("Blissymbols", "", "zbl", LanguageFamily.NotSpecified, LanguageType.Constructed) },
                {"zen", new LanguageInfo("Zenaga", "", "zen", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"zgh", new LanguageInfo("Standard Moroccan Tamazight", "", "zgh", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"zha", new LanguageInfo("Zhuang", "za", "zha", LanguageFamily.TaiKadai, LanguageType.Living) },
                {"zho", new LanguageInfo("Chinese", "zh", "zho", LanguageFamily.SinoTibetan, LanguageType.Living) },
                {"zhx", new LanguageInfo("Chinese (family)", "", "zhx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"zle", new LanguageInfo("East Slavic languages", "", "zle", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"zls", new LanguageInfo("South Slavic languages", "", "zls", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"zlw", new LanguageInfo("West Slavic languages", "", "zlw", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"znd", new LanguageInfo("Zande languages", "", "znd", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"zul", new LanguageInfo("Zulu", "zu", "zul", LanguageFamily.NigerCongo, LanguageType.Living) },
                {"zun", new LanguageInfo("Zuni", "", "zun", LanguageFamily.NotSpecified, LanguageType.Living) },
                {"zxx", new LanguageInfo("No linguistic content", "", "zxx", LanguageFamily.NotSpecified, LanguageType.NotSpecified) },
                {"zza", new LanguageInfo("Zaza", "", "zza", LanguageFamily.NotSpecified, LanguageType.Living) }
            };
        }

        private static LanguageInfo EmptyLanguage = new LanguageInfo("", "", "", LanguageFamily.NotSpecified, LanguageType.NotSpecified);

        public string Name { get; private set; }

        /// <summary>Two letter ISO 639-1 code</summary>
        public string TwoLetterIsoCode { get; private set; }

        /// <summary>Three letter ISO 639-2 code</summary>
        public string ThreeLetterIsoCode { get; private set; }

        public LanguageFamily Family { get; private set; }
        public LanguageType Type { get; private set; }

        internal LanguageInfo(string name, string twoLetterCode, string threeLetterCode, LanguageFamily family, LanguageType type)
        {
            Name = name;
            TwoLetterIsoCode = twoLetterCode;
            ThreeLetterIsoCode = threeLetterCode;
            Family = family;
            Type = type;
        }

        public static LanguageInfo GetLanguageInfo(CultureInfo culture)
        {
            if (culture == null) return null;

            LanguageInfo lang;
            if (ThreeLetterIsoToLanguage.Value.TryGetValue(culture.ThreeLetterISOLanguageName, out lang)) return lang;
            if (TwoLetterIsoToLanguage.Value.TryGetValue(culture.ThreeLetterISOLanguageName, out lang)) return lang;
            return EmptyLanguage;
        }
    }
}
